#!/bin/bash

if [ -f ".setup_complete" ]; then
    exit 0
fi

source ./env

echo "**********************************"
echo " Grey Beage Linux Template Setup *"
echo "**********************************"
echo ""

echo "This script will setup the workspace according to 'env'"
read -p "Continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1
echo ""

echo "The configured image repository is ${IMAGE_REPO}"
echo "and the cloned branch is ${IMAGE_VERSION}."
if [ $IMAGE_AS_SUBMODULE -eq 1 ]; then
    echo "The repository will be cloned as git submodule."
else
    echo "The repository will be cloned without using git submodule."
fi
read -p "Continue? (Y/N): " confirm && [[ $confirm == [yY] || $confirm == [yY][eE][sS] ]] || exit 1

if [ $IMAGE_AS_SUBMODULE -eq 1 ]; then
    git submodule add -b ${IMAGE_VERSION} ${IMAGE_REPO} images
else
    git clone --branch ${IMAGE_VERSION} ${IMAGE_REPO} images
fi

touch .setup_complete
